### ISSUE TITLE
Add gpu support on processes

### ISSUE THREAD

**Issue by Sergiodfdez** [konstellation-io/kre#125]
- Add GPU label on KRT
-  Update k8s manager to allow deploy GPU nodes

**Comment by jonasdacruz** [comment]
The proposition is to add a flag "gpu" to indicate when a process needs a gpu to work 

```
nodes:
 - name: ETL
   image: konstellation/kre-py:latest
   src: src/etl/execute_etl.py
   gpu: true
 
 - name: Execute DL Model
   image: konstellation/kre-py:latest
   src: src/execute_model/execute_model.py
   gpu: false

```
