### ISSUE TITLE
Simplify entrypoint

### ISSUE THREAD

**Issue by angelsanchez** [konstellation-io/kre#152]
Given:
```
syntax = "proto3";

package entrypoint;

message Request {
  string name = 1;
}

message Response {
  string greeting = 1;
}

service Entrypoint {
  rpc Greet (Request) returns (Response) {
  };
  rpc Salute (Request) returns (Response) {
  };
};
```
Change krt.yml from:
```
version: greeter-v1
description: Version for testing.
entrypoint:
  proto: public_input.proto
  image: konstellation/kre-runtime-entrypoint:latest
  src: src/entrypoint/entrypoint.py

nodes:
  - name: greeter
    image: konstellation/kre-py:latest
    src: src/greeter/main.py

workflows:
  - name: greeting
    entrypoint: Greet
    sequential:
      - greeter

  - name: saluting
    entrypoint: Salute
    sequential:
      - greeter
```
to
```
version: greeter-v1
description: Version for testing.

nodes:
  - name: greeter
    image: konstellation/kre-py:latest
    src: src/greeter/main.py

workflows:
  - name: greeting
    sequential:
      - greeter

  - name: saluting
    sequential:
      - greeter
```
